jobs:
  - name: airbrake-shipctl-testing
    type: runSh
    steps:
      - IN: airbrake-notifier
      - TASK:
          name: should-message-airbrake
          script:
            - echo "hello"

resources:
  - name: airbrake-userlevel-notifier
    type: notification
    integration: sample_airbrake_sub_int

  - name: airbrake-projectlevel-noifier
    type: notification
    integration: sample_airbrake_sub_int
    versionTemplate:
      recipients:
        - 215168    # only the first project ID will be considered by shipctl notify
