jobs:
  - name: old-min-sh
    type: runSh
    steps:
      - TASK:
        - script: echo "hello world"

  - name: new-min-sh
    type: runSh
    runtime:
      container: false
    steps:
      - IN: docker-login
      - TASK:
          name: echo-facts
          script: 
            - echo "power rangers forever"
            - docker pull vishnushippable/private:nginx

resources:
  - name: docker-login
    type: cliConfig
    integration: special_docker
