jobs:
  - name: airbrake-userlevel-testing
    type: runSh
    steps:
      - IN: airbrake-userlevel-notifier
      - TASK:
          name: should-message-airbrake
          script:
            - echo "hello"
            - printenv
            - git clone https://github.com/scriptnull/node.git
            - cd node
            - sudo shipctl/x86_64/Ubuntu_16.04/install.sh
            - shipctl notify airbrake-userlevel-notifier --project-id="215168" --type="deploy"  --environment="production" --username="tron" --repository="https://github.com/vishnu-shippable/local-test-cd" --revision="user.prod.$BUILD_NUMBER" --version="v4" --email="vishnu@shippable.com"
            
  - name: airbrake-projectlevel-testing
    type: runSh
    steps:
      - IN: airbrake-projectlevel-noifier
      - TASK:
          name: should-message-airbrake
          script:
            - echo "hello"
            - printenv
            - git clone https://github.com/scriptnull/node.git
            - cd node
            - sudo shipctl/x86_64/Ubuntu_16.04/install.sh
            - shipctl notify airbrake-projectlevel-noifier --type="deploy"  --environment="production" --username="pro" --repository="https://github.com/vishnu-shippable/local-test-cd" --revision="proj.prod.$BUILD_NUMBER" --version="v4" --email="vishnu@shippable.com"
            
  - name: airbrake-missing-args-testing
    type: runSh
    steps:
      - IN: airbrake-userlevel-notifier
      - TASK:
          name: should-error
          script:
            - echo "hello"
            - printenv
            - git clone https://github.com/scriptnull/node.git
            - cd node
            - sudo shipctl/x86_64/Ubuntu_16.04/install.sh
            - shipctl notify airbrake-userlevel-notifier
            
  - name: airbrake-payload-testing
    type: runSh
    steps:
      - IN: airbrake-userlevel-notifier
      - TASK:
          name: should-message-airbrake
          script:
            - echo "hello"
            - printenv
            - git clone https://github.com/scriptnull/node.git
            - cd node
            - sudo shipctl/x86_64/Ubuntu_16.04/install.sh
            - |
              echo '{ "environment": "payload", "username": "gg", "revision": "x1" }' > /tmp/p.json
            - shipctl notify airbrake-userlevel-notifier --project-id="215168" --type="deploy"  --payload="/tmp/p.json"

resources:
  - name: airbrake-userlevel-notifier
    type: notification
    integration: sample_airbrake_sub_int

  - name: airbrake-projectlevel-noifier
    type: notification
    integration: sample_airbrake_sub_int
    versionTemplate:
      recipients:
        - 215168    # only the first project ID will be considered by shipctl notify
