jobs:
  - name: old-min-sh
    type: runSh
    steps:
      - TASK:
        - script: echo "hello world"

  - name: new-min-sh
    type: runSh
    runtime:
      architecture: x86_64
      os: Ubuntu_16.04
      container: false
    steps:
      - TASK:
          name: echo-facts
          script: 
            - echo "power rangers forever"
