jobs:         
  - name: notify-irc
    type: runSh
    steps:
      - TASK:
          name: should-echo-hello
          runtime:
            options:
              imageName: drydock/u16nodall
              imageTag: v6.9.4
          script:
            - echo "hello"

