jobs:
  - name: irc-shipctl-testing
    type: runSh
    steps:
      - IN: freenode-notifier
      - TASK:
          name: should-message-irc
          script:
            - echo "hello"
            - shipctl notify irc-notifier --text="hello from runsh job"
            - echo "bye"
            
  - name: irc-notify-testing
    type: runSh
    on_start:
      - NOTIFY: freenode-notifier
      - NOTIFY: rizon-notifier
    steps:
      - TASK:
          name: should-message-irc
          script:
            - echo "hello"

resources:
  - name: freenode-notifier
    type: notification
    versionTemplate:
      method: irc
      recipients:
        - "chat.freenode.net#shiptest"

  - name: rizon-notifier
    type: notification
    versionTemplate:
      method: irc
      recipients:
        - "irc.rizon.net#shiptest"
